name: Scrape and Save BCCR today exchange

on:
  schedule:
    - cron: '5 12 * * *'

jobs:
  scrappe:
    runs-on: ubuntu-22.04
    steps:
      - run: curl https://libertadfinanciera.up.railway.app/exchange_rates/today
