name: "Today's exchange rate"

on:
  schedule:
    -cron: '*/5 * * * *'

jobs:
  scrappe:
    runs-on: ubuntu-latest
    steps:
      -name: Scrapping BCCR
      run: curl https://libertadfinanciera.up.railway.app/exchange_rates/today
